using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Collections.Immutable;
using System.Text;
using TrainOP.Generators.Models;

namespace TrainOP.Generators
{
    /// <summary>
    /// Emits exported route schemas for public factory methods.
    /// </summary>
    internal static class RouteSchemaExporter
    {
        /// <summary>
        /// Emits generated route schema source for public TrainRoute factories.
        /// </summary>
        public static void Emit(
            SourceProductionContext context,
            Compilation compilation)
        {
            if (compilation == null)
            {
                return;
            }

            var processed = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("using System;");
            source.AppendLine("using TrainOP;");
            source.AppendLine();
            source.AppendLine("namespace TrainOP.Generated.RouteSchemas");
            source.AppendLine("{");

            var hasSchemas = false;
            foreach (var syntaxTree in compilation.SyntaxTrees)
            {
                if (syntaxTree.FilePath.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                var semanticModel = compilation.GetSemanticModel(syntaxTree);
                foreach (var node in syntaxTree.GetRoot().DescendantNodes())
                {
                    if (node is not MethodDeclarationSyntax methodDeclaration)
                    {
                        continue;
                    }

                    var methodSymbol = semanticModel.GetDeclaredSymbol(methodDeclaration) as IMethodSymbol;
                    if (methodSymbol == null
                        || !FactoryAccessibilityHelper.IsExportedFactoryContract(methodSymbol)
                        || !StationSyntaxHelper.IsTrainRoute(methodSymbol.ReturnType)
                        || !processed.Add(methodSymbol))
                    {
                        continue;
                    }

                    var validation = RouteFactoryPathValidator.Validate(methodSymbol, compilation);
                    foreach (var diagnostic in validation.Diagnostics)
                    {
                        context.ReportDiagnostic(diagnostic);
                    }

                    if (!validation.IsValid)
                    {
                        continue;
                    }

                    hasSchemas = true;
                    EmitSchemaType(source, methodSymbol, validation.TerminalWagons);
                }
            }

            source.AppendLine("}");

            if (hasSchemas)
            {
                context.AddSource(
                    "TrainRoute.RouteSchemas.g.cs",
                    SourceText.From(source.ToString(), Encoding.UTF8));
            }
        }

        private static void EmitSchemaType(
            StringBuilder source,
            IMethodSymbol methodSymbol,
            ImmutableArray<WagonBinding> terminalWagons)
        {
            var ownerDisplay = methodSymbol.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var schemaTypeName = BuildSchemaTypeName(methodSymbol);
            source.Append("    [RouteSchemaFor(typeof(")
                .Append(ownerDisplay)
                .Append("), \"")
                .Append(methodSymbol.Name)
                .AppendLine("\")]");

            foreach (var wagon in terminalWagons)
            {
                source.Append("    [RouteSchemaWagon(\"")
                    .Append(EscapeString(wagon.Name))
                    .Append("\", typeof(")
                    .Append(wagon.TypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .AppendLine("))]");
            }

            source.Append("    internal static class ")
                .Append(schemaTypeName)
                .AppendLine();
            source.AppendLine("    {");
            source.Append("        public static readonly WagonSlot[] TerminalWagons = new WagonSlot[]");
            source.AppendLine();
            source.AppendLine("        {");

            for (var i = 0; i < terminalWagons.Length; i++)
            {
                var wagon = terminalWagons[i];
                source.Append("            new WagonSlot(\"")
                    .Append(EscapeString(wagon.Name))
                    .Append("\", typeof(")
                    .Append(wagon.TypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .Append("))");

                source.AppendLine(i == terminalWagons.Length - 1 ? string.Empty : ",");
            }

            source.AppendLine("        };");
            source.AppendLine("    }");
            source.AppendLine();
        }

        private static string BuildSchemaTypeName(IMethodSymbol methodSymbol)
        {
            var typeName = methodSymbol.ContainingType.Name;
            var methodName = methodSymbol.Name;
            if (typeName.Length == 0)
            {
                return methodName + "_Schema";
            }

            return typeName + "_" + methodName + "_Schema";
        }

        private static string EscapeString(string value)
        {
            return GeneratedSourceEscape.Escape(value) ?? string.Empty;
        }
    }
}
