using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace TrainOP.Generators
{
    /// <summary>
    /// Source generator reserved for travel-related extensions.
    /// </summary>
    [Generator]
    public sealed class TrainRouteTravelGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Registers a lightweight marker output for compatibility.
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, static (productionContext, compilation) =>
            {
                EmitTravelExtensions(productionContext);
            });
        }

        /// <summary>
        /// Emits a marker file to keep generator wiring stable.
        /// </summary>
        private static void EmitTravelExtensions(SourceProductionContext context)
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("namespace TrainOP");
            source.AppendLine("{");
            source.AppendLine("    internal static class TrainRouteTravelGeneratorMarker");
            source.AppendLine("    {");
            source.AppendLine("    }");
            source.AppendLine("}");

            context.AddSource(
                "TrainRouteTravel.Extensions.g.cs",
                SourceText.From(source.ToString(), Encoding.UTF8));
        }
    }
}
