using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using TrainOP.Generators.Models;

namespace TrainOP.Generators
{
    /// <summary>
    /// Source generator that emits typed Deconstruct extensions for route terminal wagons.
    /// </summary>
    [Generator]
    public sealed class TrainRouteTravelGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Registers compilation output that discovers terminal schemas and emits travel extensions.
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, static (productionContext, compilation) =>
            {
                EmitTravelExtensions(productionContext, compilation);
            });
        }

        /// <summary>
        /// Discovers terminal wagon schemas from route chains and emits extension source code.
        /// </summary>
        private static void EmitTravelExtensions(SourceProductionContext context, Compilation compilation)
        {
            var discoveredSchemas = ImmutableArray.CreateBuilder<TerminalWagonSchema>();
            var seen = new HashSet<TerminalWagonSchema>(TerminalWagonSchemaComparer.Instance);

            foreach (var tree in compilation.SyntaxTrees)
            {
                if (tree.FilePath.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                var semanticModel = compilation.GetSemanticModel(tree);
                foreach (var chain in ChainDetector.DetectChains(tree, semanticModel))
                {
                    var simulation = ChainGraphSimulator.Simulate(chain);
                    if (simulation.TerminalWagons.IsDefaultOrEmpty)
                    {
                        continue;
                    }

                    var schema = new TerminalWagonSchema(simulation.TerminalWagons);
                    if (!TerminalWagonSchemaValidator.IsValid(schema) || !seen.Add(schema))
                    {
                        continue;
                    }

                    discoveredSchemas.Add(schema);
                }
            }

            var schemasByTypeSignature = new Dictionary<string, TerminalWagonSchema>(StringComparer.Ordinal);

            foreach (var schema in discoveredSchemas)
            {
                var typeSignature = BuildCSharpDeconstructTypeSignature(schema);
                if (!schemasByTypeSignature.ContainsKey(typeSignature))
                {
                    schemasByTypeSignature[typeSignature] = schema;
                }
            }

            if (schemasByTypeSignature.Count == 0)
            {
                return;
            }

            var orderedSchemas = SelectNonAmbiguousSchemas(schemasByTypeSignature.Values)
                .OrderBy(schema => schema.SchemaId, StringComparer.Ordinal)
                .ToImmutableArray();

            if (orderedSchemas.Length == 0)
            {
                return;
            }

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("using System;");
            source.AppendLine();
            source.AppendLine("namespace TrainOP");
            source.AppendLine("{");
            source.AppendLine("    public static class TrainRouteTravelExtensions");
            source.AppendLine("    {");

            for (var i = 0; i < orderedSchemas.Length; i++)
            {
                if (i > 0)
                {
                    source.AppendLine();
                }

                EmitSchemaMembers(source, orderedSchemas[i]);
            }

            source.AppendLine("    }");
            source.AppendLine("}");

            context.AddSource(
                "TrainRouteTravel.Extensions.g.cs",
                SourceText.From(source.ToString(), Encoding.UTF8));
        }

        /// <summary>
        /// Emits Deconstruct and optional tuple helper members for one terminal schema.
        /// </summary>
        private static void EmitSchemaMembers(StringBuilder source, TerminalWagonSchema schema)
        {
            var schemaId = schema.SchemaId;
            var tupleMethod = "ToTerminalTuple_" + schemaId;
            var useTupleHelper = schema.Wagons.Length > 1;

            if (useTupleHelper)
            {
                EmitToTerminalTuple(source, schema, tupleMethod);
                source.AppendLine();
            }

            EmitDeconstruct(source, schema, useTupleHelper ? tupleMethod : null);
        }

        /// <summary>
        /// Emits a private helper that pulls all wagons from a manifest into a value tuple.
        /// </summary>
        private static void EmitToTerminalTuple(StringBuilder source, TerminalWagonSchema schema, string methodName)
        {
            source.Append("        private static (");
            for (var i = 0; i < schema.Wagons.Length; i++)
            {
                var wagon = schema.Wagons[i];
                source.Append(ManifestWagonTypes.ToManifestTypeDisplay(wagon.TypeSymbol))
                    .Append(" ")
                    .Append(wagon.Name);
                if (i < schema.Wagons.Length - 1)
                {
                    source.Append(", ");
                }
            }

            source.Append(") ").Append(methodName).AppendLine("(CargoManifest manifest)");
            source.AppendLine("        {");
            source.AppendLine("            if (manifest == null) throw new ArgumentNullException(nameof(manifest));");
            source.Append("            return (");
            for (var i = 0; i < schema.Wagons.Length; i++)
            {
                var wagon = schema.Wagons[i];
                source.Append(wagon.Name).Append(": manifest.PullWagon<")
                    .Append(ManifestWagonTypes.ToManifestTypeDisplay(wagon.TypeSymbol))
                    .Append(">(\"")
                    .Append(Escape(wagon.Name))
                    .Append("\")");
                if (i < schema.Wagons.Length - 1)
                {
                    source.Append(", ");
                }
            }

            source.AppendLine(");");
            source.AppendLine("        }");
        }

        /// <summary>
        /// Emits a RouteReport Deconstruct extension for the terminal wagon schema.
        /// </summary>
        private static void EmitDeconstruct(
            StringBuilder source,
            TerminalWagonSchema schema,
            string? tupleMethod)
        {
            source.AppendLine("        public static void Deconstruct(");
            source.AppendLine("            this RouteReport report,");
            for (var i = 0; i < schema.Wagons.Length; i++)
            {
                var wagon = schema.Wagons[i];
                source.Append("            out ")
                    .Append(ManifestWagonTypes.ToManifestTypeDisplay(wagon.TypeSymbol))
                    .Append(" ")
                    .Append(wagon.Name);
                source.AppendLine(i < schema.Wagons.Length - 1 ? "," : string.Empty);
            }

            source.AppendLine("        )");
            source.AppendLine("        {");
            source.AppendLine("            if (report == null) throw new ArgumentNullException(nameof(report));");
            if (tupleMethod != null)
            {
                source.Append("            var tuple = ").Append(tupleMethod).AppendLine("(report.TerminalSignal.Manifest);");
                for (var i = 0; i < schema.Wagons.Length; i++)
                {
                    var wagon = schema.Wagons[i];
                    source.Append("            ").Append(wagon.Name).Append(" = tuple.").Append(wagon.Name).AppendLine(";");
                }
            }
            else
            {
                var wagon = schema.Wagons[0];
                source.Append("            ")
                    .Append(wagon.Name)
                    .Append(" = report.TerminalSignal.Manifest.PullWagon<")
                    .Append(ManifestWagonTypes.ToManifestTypeDisplay(wagon.TypeSymbol))
                    .Append(">(\"")
                    .Append(Escape(wagon.Name))
                    .AppendLine("\");");
            }

            source.AppendLine("        }");
        }

        /// <summary>
        /// Selects schemas that would not cause ambiguous var deconstruction overload resolution.
        /// </summary>
        private static IEnumerable<TerminalWagonSchema> SelectNonAmbiguousSchemas(
            IEnumerable<TerminalWagonSchema> schemas)
        {
            var candidates = schemas
                .OrderByDescending(GetDeconstructSpecificity)
                .ThenBy(schema => schema.SchemaId, StringComparer.Ordinal)
                .ToList();

            var selected = new List<TerminalWagonSchema>();
            foreach (var candidate in candidates)
            {
                if (selected.Any(existing => AreVarDeconstructAmbiguous(existing, candidate)))
                {
                    continue;
                }

                selected.Add(candidate);
            }

            return selected;
        }

        /// <summary>
        /// Computes a specificity score for deconstruct overload preference.
        /// </summary>
        private static int GetDeconstructSpecificity(TerminalWagonSchema schema)
        {
            var score = 0;
            foreach (var wagon in schema.Wagons)
            {
                score += GetDeconstructTypeSpecificity(ManifestWagonTypes.ToManifestTypeDisplay(wagon.TypeSymbol));
            }

            return score;
        }

        /// <summary>
        /// Assigns a numeric specificity weight to a deconstruct type display string.
        /// </summary>
        private static int GetDeconstructTypeSpecificity(string typeDisplay)
        {
            if (typeDisplay == "global::System.String")
            {
                return 0;
            }

            if (typeDisplay == "global::System.Decimal")
            {
                return 2;
            }

            if (typeDisplay == "global::System.Int32")
            {
                return 1;
            }

            return 3;
        }

        /// <summary>
        /// Determines whether two schemas would be ambiguous for var-based deconstruction.
        /// </summary>
        private static bool AreVarDeconstructAmbiguous(TerminalWagonSchema left, TerminalWagonSchema right)
        {
            if (left.Wagons.Length != right.Wagons.Length)
            {
                return false;
            }

            for (var i = 0; i < left.Wagons.Length; i++)
            {
                var leftType = ManifestWagonTypes.ToManifestTypeDisplay(left.Wagons[i].TypeSymbol);
                var rightType = ManifestWagonTypes.ToManifestTypeDisplay(right.Wagons[i].TypeSymbol);
                if (leftType != rightType)
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Builds a type-signature key from a schema's wagon types for deduplication.
        /// </summary>
        private static string BuildCSharpDeconstructTypeSignature(TerminalWagonSchema schema)
        {
            var builder = new StringBuilder();
            for (var i = 0; i < schema.Wagons.Length; i++)
            {
                builder.Append(ManifestWagonTypes.ToManifestTypeDisplay(schema.Wagons[i].TypeSymbol))
                    .Append('|');
            }

            return builder.ToString();
        }

        /// <summary>
        /// Escapes string literals for inclusion in generated source code.
        /// </summary>
        private static string Escape(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
