using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Text;

namespace TrainOP.Generators
{
    /// <summary>
    /// Emits the generated route schemas source file for public factory methods.
    /// </summary>
    internal static class RouteSchemasFile
    {
        internal const string SourceHintName = "TrainRoute.RouteSchemas.g.cs";

        /// <summary>
        /// Discovers exported factories and emits route schema source when present.
        /// </summary>
        internal static void AddSource(SourceProductionContext context, Compilation compilation)
        {
            if (compilation == null)
            {
                return;
            }

            var processed = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("using System;");
            source.AppendLine("using TrainOP;");
            source.AppendLine();
            source.AppendLine("namespace TrainOP.Generated.RouteSchemas");
            source.AppendLine("{");

            var hasSchemas = false;
            foreach (var syntaxTree in compilation.SyntaxTrees)
            {
                if (syntaxTree.FilePath.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                var semanticModel = compilation.GetSemanticModel(syntaxTree);
                foreach (var node in syntaxTree.GetRoot().DescendantNodes())
                {
                    if (node is not MethodDeclarationSyntax methodDeclaration)
                    {
                        continue;
                    }

                    var methodSymbol = semanticModel.GetDeclaredSymbol(methodDeclaration) as IMethodSymbol;
                    if (methodSymbol == null
                        || !FactoryAccessibilityHelper.IsExportedFactoryContract(methodSymbol)
                        || !StationSyntaxHelper.IsTrainRoute(methodSymbol.ReturnType)
                        || !processed.Add(methodSymbol))
                    {
                        continue;
                    }

                    var validation = RouteFactoryPathValidator.Validate(methodSymbol, compilation);
                    foreach (var diagnostic in validation.Diagnostics)
                    {
                        context.ReportDiagnostic(diagnostic);
                    }

                    if (!validation.IsValid)
                    {
                        continue;
                    }

                    hasSchemas = true;
                    new RouteFactorySchema(methodSymbol, validation.TerminalWagons).Emit(source);
                }
            }

            source.AppendLine("}");

            if (hasSchemas)
            {
                context.AddSource(SourceHintName, SourceText.From(source.ToString(), Encoding.UTF8));
            }
        }
    }
}
