using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace TrainOP.Generators
{
    /// <summary>
    /// Emits the generated route schemas source file for public factory methods.
    /// Descriptors are IR (<see cref="SchemaDescriptor"/>); call from <see cref="GenerationEmit.EmitAll"/> only.
    /// </summary>
    internal static class RouteSchemasFile
    {
        internal const string SourceHintName = "TrainRoute.RouteSchemas.g.cs";

        /// <summary>
        /// Emits route schema source from already-built descriptors (no discovery / no diagnostics).
        /// Sole emit path — diagnostics are reported by <see cref="GenerationEmit.EmitAll"/> from the model.
        /// </summary>
        internal static void AddSource(
            SourceProductionContext context,
            ImmutableArray<SchemaDescriptor> descriptors)
        {
            if (descriptors.IsDefaultOrEmpty)
            {
                return;
            }

            var writer = new CodegenWriter();
            writer.AppendRawLine("// <auto-generated />");
            writer.AppendRawLine("using System;");
            writer.AppendRawLine("using TrainOP;");
            writer.AppendLine();
            writer.AppendRawLine("namespace TrainOP.Generated.RouteSchemas");
            writer.AppendRawLine("{");
            using (writer.PushIndent())
            {
                for (var i = 0; i < descriptors.Length; i++)
                {
                    var descriptor = descriptors[i];
                    if (descriptor == null)
                    {
                        continue;
                    }

                    new RouteFactorySchema(descriptor).Emit(writer);
                }
            }

            writer.AppendRawLine("}");
            context.AddSource(SourceHintName, SourceText.From(writer.ToString(), Encoding.UTF8));
        }
    }
}
