<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>TrainOP</RootNamespace>

    <PackageId>TrainOP</PackageId>
    <Version>0.14.0</Version>
    <Authors>Criperum</Authors>
    <Description>Railway Oriented Programming для .NET (runtime + source generators / analyzer)</Description>
    <PackageTags>railway;rop;functional;source-generator;analyzer;roslyn</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/moragfullrest-cmyk/TrainOP.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/moragfullrest-cmyk/TrainOP</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <GeneratePackageOnBuild Condition="'$(Configuration)' != 'Release'">false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrainOP.Generators\TrainOP.Generators.csproj"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\TrainOP.Generators\bin\$(Configuration)\netstandard2.0\TrainOP.Generators.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\TrainOP.Generators\build\TrainOP.Generators.targets"
          Pack="true"
          PackagePath="build\TrainOP.targets"
          Visible="false" />
  </ItemGroup>
</Project>
